package com.ksyun.agent.core.exception;

/**
 * Agent 框架统一错误码。
 */
public enum AgentErrorCode {

    INVALID_ARGUMENT,
    AGENT_NOT_FOUND,
    TOOL_NOT_FOUND,
    TOOL_ACCESS_DENIED,
    APPROVAL_REQUIRED,
    CHECKPOINT_NOT_FOUND,
    MAX_ITERATIONS_REACHED,
    MODEL_NOT_AVAILABLE,
    MODEL_INVOCATION_FAILED,
    SUPERVISOR_NOT_FOUND,
    TOOL_EXECUTION_FAILED,

    // --- 身份与权限 ---
    AUTHENTICATION_FAILED,
    INVALID_CREDENTIALS,
    SESSION_NOT_FOUND,
    SESSION_INVALID,
    SESSION_EXPIRED,
    USER_NOT_FOUND,
    USER_DISABLED,
    ROLE_NOT_FOUND,
    ROLE_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    PERMISSION_DENIED,

    // --- Checkpoint 与审批 ---
    CHECKPOINT_CONFLICT,
    RUN_SUSPENDED,
    APPROVAL_NOT_FOUND,
    APPROVAL_ALREADY_DECIDED,
    INVALID_APPROVAL_DECISION,
    APPROVAL_REJECTED,
    CHECKPOINT_NOT_RESUMABLE,
    RUN_ALREADY_RESUMING,
    RESUME_FAILED,

    // --- 上下文管理 ---
    INVALID_MESSAGE_HISTORY,
    TOOL_MESSAGE_PAIRING_FAILED,
    INVALID_CONTEXT_CONFIGURATION,
    CONTEXT_BUDGET_EXCEEDED,
    TOKEN_COUNT_FAILED,
    CONTEXT_PROCESSING_FAILED,
    CONTEXT_SUMMARY_FAILED,
    INVALID_CONTEXT_SUMMARY_OUTPUT,
    INVALID_CONTEXT_WINDOW_STATE,

    // --- 长期记忆 ---
    MEMORY_NOT_FOUND,
    INVALID_MEMORY_ENTRY,
    MEMORY_STORE_FAILED,

    // --- 线程短期记忆 ---
    INVALID_THREAD_ID,
    THREAD_NOT_FOUND,
    THREAD_BUSY,
    THREAD_SUSPENDED,
    THREAD_PARTICIPANT_MISMATCH,
    THREAD_CHECKPOINT_INVALID,

    INTERNAL_ERROR
}
