package com.ksyun.agent.core.exception;

/**
 * Agent 框架统一错误码。
 */
public enum AgentErrorCode {

    INVALID_ARGUMENT,
    AGENT_NOT_FOUND,
    TOOL_NOT_FOUND,
    TOOL_ACCESS_DENIED,
    APPROVAL_REQUIRED,
    CHECKPOINT_NOT_FOUND,
    MAX_ITERATIONS_REACHED,
    MODEL_NOT_AVAILABLE,
    MODEL_INVOCATION_FAILED,
    SUPERVISOR_NOT_FOUND,
    TOOL_EXECUTION_FAILED,

    // --- 身份与权限 ---
    AUTHENTICATION_FAILED,
    INVALID_CREDENTIALS,
    SESSION_NOT_FOUND,
    SESSION_INVALID,
    SESSION_EXPIRED,
    USER_NOT_FOUND,
    USER_DISABLED,
    ROLE_NOT_FOUND,
    ROLE_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    PERMISSION_DENIED,

    INTERNAL_ERROR
}
